version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bulletin_board
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  app:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
    ports:
      - "3001:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
    depends_on:
      - app

volumes:
  postgres_data:
